version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/weatherapp
hooks:
  BeforeInstall:
    - location: /scripts/before_install.sh
      runas: ec2-user
  AfterInstall:
    - location: /scripts/set_vars.sh
      runas: ec2-user
    - location: /scripts/app_start.sh
      runas: ec2-user


